### ISSUE TITLE
Possibility to run locally to avoid Drive quota being exceeded?

### ISSUE THREAD

**Issue by JanKjellin** [tg-bomze/Face-Depixelizer#10]
Is there a way to run this locally or to point it to, say, one's own Google Drive to avoid the issue of qouta being exceeded?

**Comment by Acurisu** [comment]
There are multiple ways to achieve this and I will list a few that came to my mind.

**Local (persistent)**
You could directly run [PULSE](https://github.com/adamian98/pulse) on a local instance. If you do that you don't even need to download the files manually as it will download them on your first run. If the cache gets cleared just do what the next method wants you to do but on your local instance of PULSE.

**Online (temporary)**
You could download the files and host them wherever you want and manually change the links after the colab downloaded PULSE at [synthesis.pt](https://github.com/adamian98/pulse/blob/154679cf2e178afe923daa76fa820b1d6176be42/PULSE.py#L23) ([mapping.pt](https://github.com/adamian98/pulse/blob/154679cf2e178afe923daa76fa820b1d6176be42/PULSE.py#L37) and [shape_predictor_68_face_landmarks.dat](https://github.com/adamian98/pulse/blob/154679cf2e178afe923daa76fa820b1d6176be42/align_face.py#L34) are required too depending on what you are doing).
Instead of changing the links and hosting the files you could just upload the files into a directory of the colab and point PULSE to the correct location.

**Online (persistent)**
Fork [PULSE](https://github.com/adamian98/pulse) and change the links like in the method I mentioned beforehand.
Then copy the colab to your drive and change [!git clone](https://github.com/tg-bomze/Face-Depixelizer/blob/fefb2cf489ccf9e355a4d8471aa25bfbaefe9d1b/Face_Depixelizer_Eng.ipynb#L87) to point to your fork (don't forget to save).
<img width="200" alt="Copy to Drive" src="https://user-images.githubusercontent.com/17300231/85407483-8cfcf800-b563-11ea-8d53-f512043583bc.png">

**Local (persistent)**
You could mix the first and second option by downloading the colab and running it using Jupyter.

The files for manual download:
[synthesis.pt](https://drive.google.com/uc?id=1TCViX1YpQyRsklTVYEJwdbmK91vklCo8)
[mapping.pt](https://drive.google.com/uc?id=14R6iHGf5iuVx3DMNsACAl7eBr7Vdpd0k)
[shape_predictor_68_face_landmarks.dat](https://drive.google.com/uc?id=1huhv8PYpNNKbGCLOaYUjOgR1pY5pmbJx)

**Comment by JanKjellin** [comment]
Awesome! I'll look into those options.

Thank you. :)

**Comment by AlbertoCasasOrtiz** [comment]
Hi!

Following the ideas of @Acurisu, I have managed to make it work when this error happens. I had to change a few iles of code in my colab session but it is straightforward.

1.  Execute the code, it will downloading all necessary files into the colab session, and the quota exceeded error appears.

2. Download the weights of the network manually from [this link](https://drive.google.com/uc?id=1TCViX1YpQyRsklTVYEJwdbmK91vklCo8). This is the first link that appears in the error message.

3. Once you have the weights (a file called synthesis.pt), put it in the folder of the colab filesystem called pulse.

4. In the file PULSE.py, change the following lines of code:

```
    # Lines to delete (or comment):
    with open_url("https://drive.google.com/uc?id=1TCViX1YpQyRsklTVYEJwdbmK91vklCo8", cache_dir=cache_dir, verbose=verbose) as f:
        self.synthesis.load_state_dict(torch.load(f))
```
```
    # Lines to add:
    with open("/content/pulse/synthesis.pt", "rb") as f:
        self.synthesis.load_state_dict(torch.load(f))
```

5. Upload your photo, either by using the upload button, or by uploading the photo manually into the folder pulse/input/. The name of the image should be face.png.

It worked for me following those steps, I hope it helps!
