### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mfcharaf** [tg-bomze/Face-Depixelizer#2]
I'm getting this error while running project on colab : 
`FileNotFoundError: [Errno 2] No such file or directory: '/content/pulse/runs/face.png'`

**Comment by FlashlightET** [comment]
same

**Comment by LeChn** [comment]
same

**Comment by Acurisu** [comment]
The error (in this case / currently) occurs because the google drive quota is reached. Try again tomorrow.

The cell shows the "OSError: Google Drive quota exceeded" only for a short period of time.

In the future please refrain from writing things like "same" and use the reactions instead.

**Comment by antim0118** [comment]
> The cell shows the "OSError: Google Drive quota exceeded" only for a short period of time.

as for me, it shows torch-related error

![err](https://user-images.githubusercontent.com/22983870/85211965-89048680-b367-11ea-989c-1039e943d43d.png)

**Comment by Acurisu** [comment]
> as for me, it shows torch-related error

Yes, it can (and will) show other errors in this short flicker. This is due to the fact that PULSE can return different errors other than the google quota one. The problem with this colab is that the author executes PULSE just to clear the output afterwards ([see](https://github.com/tg-bomze/Face-Depixelizer/blob/894351cba561f0ca55a24e2b95408ab40dcd2546/Face_Depixelizer_Eng.ipynb#L161)) and then continues to execute the rest which expects a generated image and thus results in the FileNotFound error if an error has occurred during the execution of PULSE.

**Comment by Acurisu** [comment]
@tg-bomze 
I suggest removing `clear_output()` after `!python run.py` as this will let people see the error that was raised in PULSE.

Я предлагаю удалить `clear_output()` после `!python run.py`, так как это позволит увидеть ошибку, которая была поднята в PULSE.

**Comment by tg-bomze** [comment]
@Acurisu 

done
